version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_USER=your-db-user
      - POSTGRES_PASSWORD=your-db-password
      - POSTGRES_DB=your-db-name

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
